//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creditor_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Creditor_Account()
        {
            this.Transaction_Out = new HashSet<Transaction_Out>();
        }
    
        public int Creditor_Account_Id { get; set; }
        public int Creditor_Id { get; set; }
        public int Balance { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
        public Nullable<int> Min_Balance { get; set; }
    
        public virtual Creditor Creditor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Out> Transaction_Out { get; set; }
    }
}
