//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creditor_Rank
    {
        public int Creditor_Rank_Id { get; set; }
        public int Creditor_Id { get; set; }
        public Nullable<int> Associate_Counter { get; set; }
        public Nullable<double> Delta_ROI { get; set; }
    
        public virtual Creditor Creditor { get; set; }
    }
}
