//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debtor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Debtor()
        {
            this.Associate = new HashSet<Associate>();
            this.Transaction_Out1 = new HashSet<Transaction_Out>();
        }
    
        public int Debtor_Id { get; set; }
        public string username { get; set; }
        public Nullable<float> APR { get; set; }
        public Nullable<float> EAPR { get; set; }
        public bool Available { get; set; }
        public int Debet { get; set; }
        public int Finapp_Debet { get; set; }
        public Nullable<System.DateTime> Queue_Date { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
        public float Delta_APR { get; set; }
        public Nullable<int> Trials { get; set; }
        public Nullable<int> AssociateCounter { get; set; }
        public Nullable<int> LastAssociate { get; set; }
        public Nullable<int> Savings { get; set; }
        public Nullable<int> HaveMoney { get; set; }
        public Nullable<int> ActualMoney { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Associate> Associate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Out> Transaction_Out1 { get; set; }
    }
}
