//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Summary
    {
        public int Summary_Id { get; set; }
        public int Associate_Id { get; set; }
        public Nullable<int> Debet_Average { get; set; }
        public Nullable<int> Balance_Average { get; set; }
        public Nullable<int> Savings_Average { get; set; }
        public Nullable<int> Profits_Average { get; set; }
        public Nullable<int> Savings_Average_Percentage { get; set; }
        public Nullable<int> Profits_Average_Percentage { get; set; }
        public Nullable<int> Profits_Sum { get; set; }
        public Nullable<int> Savings_Sum { get; set; }
        public Nullable<int> Balance_Sum { get; set; }
        public Nullable<int> Debet_Sum { get; set; }
        public Nullable<int> Debtors { get; set; }
        public Nullable<int> Creditors { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<System.DateTime> DateOfSummary { get; set; }
        public Nullable<int> Turnover { get; set; }
    
        public virtual Associate Associate { get; set; }
    }
}
