//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Out
    {
        public int Transaction_Out_Id { get; set; }
        public int Ammount { get; set; }
        public Nullable<System.DateTime> Date_Of_Transaction { get; set; }
        public int Creditor_Account_Id { get; set; }
        public int Debtor_Account_Id { get; set; }
        public Nullable<float> ROI { get; set; }
        public Nullable<int> Finapp_Debetor { get; set; }
        public Nullable<int> Finapp_Creditor { get; set; }
        public int Day_Access_To_Funds { get; set; }
        public Nullable<int> Creditor_Benefits_Per_Annum { get; set; }
        public Nullable<int> Debtor_Benefits_Per_Annum { get; set; }
        public int Associate_Id { get; set; }
        public Nullable<int> Creditor_Id { get; set; }
        public Nullable<int> Debtor_Id { get; set; }
        public Nullable<int> ActualCreditorBenefits { get; set; }
        public Nullable<int> CreditorBenefits { get; set; }
        public Nullable<int> DebtorSavings { get; set; }
        public Nullable<int> AssociateDay { get; set; }
    
        public virtual Associate Associate { get; set; }
        public virtual Creditor Creditor { get; set; }
        public virtual Debtor Debtor { get; set; }
    }
}
